# Generated by Django 3.2.5 on 2021-07-07 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'abilities',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField()),
                ('is_mega', models.BooleanField()),
                ('form_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('accuracy', models.SmallIntegerField()),
                ('effect_chance', models.SmallIntegerField()),
                ('power_points', models.SmallIntegerField()),
                ('power', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'moves',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('is_legendary', models.BooleanField()),
                ('is_mythical', models.BooleanField()),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveSmallIntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('base_experience', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_default', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('location_area_encounters', models.CharField(max_length=100)),
                ('abilities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.abilities')),
                ('forms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.forms')),
                ('moves', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.moves')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.species')),
                ('types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.types')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pokemon',
            },
        ),
    ]
